<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="2" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-17T16:58:29Z" name="Suite" finished-at="2024-11-17T16:59:02Z" duration-ms="32968">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.loginErrorValidation()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" name="loginErrorValidation" class="E2EPractiseProject.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="purchaseorder">
        <method signature="StandAloneTest.submitOrder(java.util.HashMap)[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" name="submitOrder" class="E2EPractiseProject.StandAloneTest"/>
      </group> <!-- purchaseorder -->
    </groups>
    <test started-at="2024-11-17T16:58:29Z" name="ErrorValidation" finished-at="2024-11-17T16:59:00Z" duration-ms="30667">
      <class name="E2EPractiseProject.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:29Z" name="launchApplication" finished-at="2024-11-17T16:58:32Z" duration-ms="2641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:32Z" name="loginErrorValidation" finished-at="2024-11-17T16:58:41Z" duration-ms="9204" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at E2EPractiseProject.ErrorValidation.loginErrorValidation(ErrorValidation.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:41Z" name="tearDown" finished-at="2024-11-17T16:58:41Z" duration-ms="95" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:41Z" name="launchApplication" finished-at="2024-11-17T16:58:49Z" duration-ms="8502" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:49Z" name="loginErrorValidation" finished-at="2024-11-17T16:58:51Z" duration-ms="1914" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at E2EPractiseProject.ErrorValidation.loginErrorValidation(ErrorValidation.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:52Z" name="tearDown" finished-at="2024-11-17T16:58:52Z" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:52Z" name="launchApplication" finished-at="2024-11-17T16:58:57Z" duration-ms="4718" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="prodErrValidation()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:58:57Z" name="prodErrValidation" finished-at="2024-11-17T16:59:00Z" duration-ms="2531" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prodErrValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:E2EPractiseProject.ErrorValidation@4a3329b9]" started-at="2024-11-17T16:59:00Z" name="tearDown" finished-at="2024-11-17T16:59:00Z" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- E2EPractiseProject.ErrorValidation -->
    </test> <!-- ErrorValidation -->
    <test started-at="2024-11-17T16:58:29Z" name="StandAloneTest" finished-at="2024-11-17T16:59:02Z" duration-ms="32968">
      <class name="E2EPractiseProject.StandAloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" started-at="2024-11-17T16:58:29Z" name="launchApplication" finished-at="2024-11-17T16:58:32Z" duration-ms="2440" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" started-at="2024-11-17T16:58:32Z" name="submitOrder" data-provider="getData" finished-at="2024-11-17T16:58:49Z" duration-ms="17604" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Password@123, product=ZARA COAT 3, email=shimpimanisha21@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" started-at="2024-11-17T16:58:49Z" name="tearDown" finished-at="2024-11-17T16:58:49Z" duration-ms="243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" started-at="2024-11-17T16:58:49Z" name="launchApplication" finished-at="2024-11-17T16:58:52Z" duration-ms="2028" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" started-at="2024-11-17T16:58:52Z" name="submitOrder" data-provider="getData" finished-at="2024-11-17T16:59:02Z" duration-ms="9982" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Password@123, product=ADIDAS ORIGINAL, email=vrshimpi5@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at E2EPractiseProject.StandAloneTest.submitOrder(StandAloneTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" started-at="2024-11-17T16:59:02Z" name="tearDown" finished-at="2024-11-17T16:59:02Z" duration-ms="230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="orderHistoryTest()[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6]" started-at="2024-11-17T16:59:02Z" name="orderHistoryTest" finished-at="2024-11-17T16:59:02Z" depends-on-methods="E2EPractiseProject.StandAloneTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method StandAloneTest.orderHistoryTest()[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method StandAloneTest.orderHistoryTest()[pri:0, instance:E2EPractiseProject.StandAloneTest@4f2c9ba6] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
      </class> <!-- E2EPractiseProject.StandAloneTest -->
    </test> <!-- StandAloneTest -->
  </suite> <!-- Suite -->
</testng-results>
